# Generated by Django 5.1.4 on 2024-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_level',
            field=models.CharField(default=0, max_length=10, verbose_name='Уровень иерархии торговой компании'),
            preserve_default=False,
        ),
    ]
